### ISSUE TITLE
Do we need to include any class ?

### ISSUE THREAD

**Issue by pressaholic** [A5hleyRich/wp-background-processing-example#1]
Hi there,

Thanks for this brilliant idea and tool :)

I would like to use your tool in my existing plugin. I cannot see, on your example plugin where do you require your classes definiton.

Thanks

**Comment by A5hleyRich** [comment]
WP Background Processing is installed as a plugin, therefore the classes are available upon activation.

https://github.com/A5hleyRich/wp-background-processing/blob/master/wp-background-processing.php
